/**
 * Extends Hono into a self-contained application server that handles route
 * discovery, registration, and port binding.
 *
 * Route discovery is environment-aware: in dev, routes are found at runtime
 * via filesystem glob; in prod, they come from the pre-generated static
 * route map built by the cartographer.
 */

import { Hono } from "hono"
import { METHODS } from "hono/router"
import { serveStatic } from "hono/bun"
import type { Route, HttpMethod } from "../../types/Route"
import config from "../../config.json"
import { requireAuth } from "../../middleware/requireAuth"
import { validateBody } from "../../middleware/validateBody"
import { derivePath } from "../routing/derivePath"

/**
 * Application HTTP server.
 *
 * Inherits all of Hono's routing, middleware, and context APIs. Adds route
 * discovery and registration on top. The typical lifecycle is:
 *
 * ```ts
 * const server = new Server()
 * await server.constructRoutes()
 * server.start()
 * ```
 */
export class Server extends Hono {
  /**
   * Binds the server to the port specified in `config.json` via `Bun.serve`.
   * Must be called after `constructRoutes` has registered all endpoints.
   */
  start() {
    Bun.serve({ fetch: this.fetch, port: config.port })
    console.log(`[Server] Listening on port ${config.port}`)
  }

  /**
   * Discovers and registers all route files with the Hono router.
   *
   * Calls the private `discoverRoutes` to load the route record, then iterates
   * each entry checking every HTTP method. When a route defines a handler for
   * a given method, a middleware chain is built and registered via
   * `this.on([method], [path], ...chain)`.
   */
  async constructRoutes() {
    const routes = await this.discoverRoutes()

    for (const [path, route] of Object.entries(routes)) {
      for (const method of METHODS) {
        const key = method.toUpperCase() as HttpMethod
        const entry = route[key]
        if (!entry) continue

        const isConfig = typeof entry === "object" && "handler" in entry
        const handler = isConfig ? entry.handler : entry
        const bodySchema = isConfig ? entry.body : undefined

        const chain = [
          ...(route.authenticated ? [requireAuth] : []),
          ...(bodySchema ? [validateBody(bodySchema)] : []),
          ...(route.middleware ?? []),
          handler,
        ]
        this.on([method], [path], ...chain)
      }
    }

    console.log(`[Server] Registered ${Object.keys(routes).length} routes`)
    this.mountWebApp()
  }

  /**
   * Serves the web app at `/`.
   *
   * In production, serves pre-built static files from `dist/public/` with
   * an SPA fallback to `index.html` for client-side routing.
   * In development, proxies all non-API requests to the Vite dev server
   * so HMR and other dev features work seamlessly.
   */
  private mountWebApp() {
    if (process.env.NODE_ENV === "production") {
      const root = import.meta.dir + "/../public"

      this.use("/*", serveStatic({ root }))
      this.get("*", serveStatic({ root, path: "index.html" }))
      console.log("[Server] Mounted web app (static files)")
    } else {
      console.log("[Server] Mounted web app (dev proxy)")
      this.all("*", async (c) => {
        const url = new URL(c.req.url)
        url.port = "5173"
        const res = await fetch(url.toString(), {
          method: c.req.method,
          headers: c.req.raw.headers,
          body: c.req.raw.body,
        })
        return res
      })
    }
  }

  /**
   * Loads route definitions based on the current environment.
   *
   * In dev, scans `src/routes/` with `Bun.Glob` and dynamically imports every
   * `.ts` file. In prod, imports the static `_route.map.ts` generated by the
   * cartographer build script.
   */
  private async discoverRoutes(): Promise<Record<string, Route>> {
    if (process.env.NODE_ENV !== "production") {
      const glob = new Bun.Glob("**/*.ts")
      const dir = import.meta.dir + "/../../routes"
      const routes: Record<string, Route> = {}

      for await (const path of glob.scan(dir)) {
        const mod = await import(`../../routes/${path}`)
        routes[derivePath(path)] = mod.default
      }

      return routes
    }

    const map = await import("../../_route.map")
    return map.routes
  }
}
