/**
 * Build-time web asset embedding script — the cartographer's counterpart for
 * the web app. Scans the built web app in `apps/web/dist/` and generates
 * `src/_asset.map.ts`, which imports every file with Bun's `file` loader and
 * exports them keyed by the URL path they are served at.
 *
 * Importing the files is what makes them part of the build: `Bun.build` copies
 * each one next to the bundle, and `bun build --compile` embeds each one in the
 * executable's virtual filesystem. Serving from disk relative to the binary
 * would 404 once the executable is moved, so the web app must go through here.
 *
 * Run automatically by `scripts/build.ts` after the web app is built. The
 * generated file is a build artifact and is not checked into version control.
 */

import { existsSync } from "node:fs"
import { relative } from "node:path"

// ---------- Paths ---------- //

const webDist = `${import.meta.dir}/../../web/dist`
const outPath = `${import.meta.dir}/../src/_asset.map.ts`

// ---------- Generation ---------- //

// Refuse to emit an empty map, which would silently ship a server with no UI.
// `--allow-empty` exists only so a fresh checkout can type check without
// building the web app first.
const allowEmpty = process.argv.includes("--allow-empty")
const hasWebBuild = existsSync(`${webDist}/index.html`)

if (!hasWebBuild && !allowEmpty) {
  console.error("Asset map: apps/web/dist/index.html is missing — build the web app first")
  process.exit(1)
}

const imports: string[] = []
const entries: string[] = []
let i = 0

// Map every built file to the URL path Vite expects it to be served at
const files = hasWebBuild ? new Bun.Glob("**/*").scan({ cwd: webDist, dot: false }) : []
for await (const path of files) {
  const name = `asset${i++}`
  const importPath = relative(`${import.meta.dir}/../src`, `${webDist}/${path}`)
  imports.push(`import ${name} from ${JSON.stringify(importPath)} with { type: "file" }`)
  entries.push(`  ${JSON.stringify(`/${path}`)}: ${name}`)
}

// TypeScript cannot type file-loader imports of arbitrary extensions, so the
// generated module opts out of checking and declares its export type itself
const output = `// @ts-nocheck — generated by scripts/assetmap.ts; file-loader imports are untypeable
${imports.join("\n")}

/** URL path → embedded file path, resolvable with \`Bun.file\`. */
export const assets: Record<string, string> = {
${entries.join(",\n")}
}
`

await Bun.write(outPath, output)
console.log(`Asset map: embedded ${entries.length} web file(s) → src/_asset.map.ts`)
